### ISSUE TITLE
Error evaluating variable: CloudClientException: Retries exceeded

### ISSUE THREAD

**Issue by federicobond** [DevCycleHQ/python-server-sdk#62]
I got this error in the logs after I lost connectivity in my dev computer. The page I was loading that was requesting the feature flag just hanged. This could be a serious issue if the SDK loses connectivity with DevCycle in a production environment.

It should return the default value if it cannot evaluate the variable in a relatively short amount of time.

**Comment by rob-odwyer** [comment]
Hey @federicobond, thanks for the bug report!

Could you give a code sample of how you're using the SDK, including the setup of the client and how you're requesting the variable?

It sounds from the error like you're using the Cloud Bucketing SDK, which makes requests to an API for every variable evaluation. If you're able to use the Local Bucketing SDK, that should avoid waiting on a response and be significantly faster.

**Comment by federicobond** [comment]
Thank you for the prompt response @rob-odwyer! Yes, I am using the Cloud Bucketing SDK through the OpenFeature provider.

I tried the Local Bucketing SDK a while ago but in its default configuration it felt too chatty. IIRC I was seeing request traces every second for every worker in every instance and I don't have enough traffic to amortize that cost.

Regardless of that, as long as DevCycle is up I haven't had any performance problems, but if the client loses connectivity for whatever reason it was a bit scary seeing my requests blocked while evaluating a flag, and I believe the SDK should be much more aggressive in returning a default or cached value in those cases.

**Comment by jsalaber** [comment]
Hi @federicobond,

There is an option you can configure in the start options of the Cloud Bucketing client to change the request timeout, the number of request retries, and even the retry delay: 

https://github.com/DevCycleHQ/python-server-sdk/blob/main/devcycle_python_sdk/options.py#L22. If you think our default of 5 seconds to timeout the request is too long you may configure it here.

To your point of the local bucketing sdk being too chatty, that might have to do with the config polling that is polling changes for the CDN config so that the SDK has the most up to date data to use. The polling interval is also configurable: 

https://github.com/DevCycleHQ/python-server-sdk/blob/b17a6a577d0bd781a11bfdbe0a981dce08216164/devcycle_python_sdk/options.py#L36C9-L36C35

**Comment by nikolasleblanc** [comment]
Hey @federicobond wondering if you've had a chance to review @jsalaber's response? Let us know if there's anything more we can do to help!

**Comment by nikolasleblanc** [comment]
Hey @federicobond we're going to close this ticket for now but please feel free to re-open or submit another one if you continue to run into trouble.
